---
- name: "Applications Common - Create Application Directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    recurse: no
    follow: no
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ application_directories }}"