---
- name: "Applications Common - Create Application LVM"
  lvg:
    vg: "vg_{{ application_account_login }}"
    pvs: "{{ srv_pv_path }}/{{ item }}"
  with_items: "{{ srv_hdd_app_list }}"

- name: "Applications Common - Create Application LVM - Logical volume (lv_app)."
  lvol:
    vg: "vg_{{ application_account_login }}"
    lv: lv_app
    size: "{{ srv_lv_app_size }}"

- name: "Applications Common - Create Application LVM - Logical volume (lv_log)."
  lvol:
    vg: "vg_{{ application_account_login }}"
    lv: lv_log
    size: "{{ srv_lv_log_size }}"

- name: "Applications Common - Create Application LVM - Logical volume (lv_data)."
  lvol:
    vg: "vg_{{ application_account_login }}"
    lv: lv_data
    size: "{{ srv_lv_data_size }}"
