---
- name: "Applications Common - Create Application XFS Filesystems for (lv_app)"
  filesystem:
    fstype: xfs
    resizefs: yes
    dev: /dev/mapper/vg_{{ application_account_login }}-lv_app


- name: "Applications Common - Create Application XFS Filesystems for (lv_log)"
  filesystem:
    fstype: xfs
    resizefs: yes
    dev: /dev/mapper/vg_{{ application_account_login }}-lv_log


- name: "Applications Common - Create Application XFS Filesystems for (lv_data)"
  filesystem:
    fstype: xfs
    resizefs: yes
    dev: /dev/mapper/vg_{{ application_account_login }}-lv_data
