---
# Loading OS correct vars
- name: Loading OS correct vars
  import_tasks: load_vars.yml
  tags:
    - load_vars

- name: "Print role Vars"
  ansible.builtin.debug:
    msg: 
      - "app_common_role_debug : {{ app_common_role_debug }}"
      - "application : {{ application }}"
      - "application_users : {{ application_users }}"
      - "application_lvms_create : {{ application_lvms_create }}"
      - "application_vgs : {{ application_vgs }}"

  when: app_common_role_debug == true
  tags:
    - role_debug

# Run tasks.
- name: Deploy common role on RHEL Familly
  import_tasks: rhel-main.yml
  when: ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  tags:
    - os-commons-rhel

- name: Deploy common role on Debian Familly
  import_tasks: debian-main.yml
  when: (ansible_facts['os_family'] == "Debian")
  tags:
    - os-common-debian